name: Release @next

on:
  push:
    branches: [main]

jobs:
  release-next:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - run: pnpm i

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        id: commit

      - run: pnpm run packages:bump 0.0.0-next.${{ steps.commit.outputs.short_sha }} --yes --no-push

      - run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: pnpm run packages:publish --tag=next
        env:
          NPM_CONFIG_PROVENANCE: true
